version: "2"
services:
  client:
    image: client
    build: client
    ports:
      - "8081:8080" 
    links:
      - serveur
  serveur:
    image: serveur
    build: serveur
    ports:
      - "3000:3000"
    links:
      - mongodb
  sockets:
    image: socket
    build: socket
    ports:
      - "3001:3001"
  mongodb:
    image: mongo
    ports:
      - "8000:27017"